version: '3.8'

services: 
    backend:
        build:
            context: ./backend
            dockerfile: ./Dockerfile.dockerfile
        ports:
            - "5000:5000"
    frontend:
        build:
            context: ./frontend
            dockerfile: ./Dockerfile.dockerfile
        ports:
            - "3000:3000"
        links:
            - "backend:be"